### ISSUE TITLE
Have problems with different mods

### ISSUE THREAD

**Issue by XMZO** [Shepherd23333/ProjectEu#1]
**crash-reports:** https://mclo.gs/CtevKzJ

**The relevant part of the error:**
Caused by: java.lang.NoSuchMethodError: 'void moze_intel.projecte.api.proxy.IEMCProxy.registerCustomEMC(net.minecraft.item.ItemStack, long)'
	at nc.integration.projecte.NCProjectE.addEMCValues(NCProjectE.java:86)
	at nc.integration.projecte.NCProjectE.addIngotEMCValues(NCProjectE.java:92)
	at nc.integration.projecte.NCProjectE.addEMCValues(NCProjectE.java:16)
	at nc.proxy.CommonProxy.postInit(CommonProxy.java:184)
	at nc.proxy.ClientProxy.postInit(ClientProxy.java:54)
	at nc.NuclearCraft.postInit(NuclearCraft.java:49)

**Comment by XMZO** [comment]
望修复

**Comment by XMZO** [comment]
望修复，谢谢

**Comment by XMZO** [comment]
Replace with NuclearCraft: Overhauled with Security Craft does the same thing

**Comment by XMZO** [comment]
很多mod自动添加emc时都用的long，能不能搞个自动转成BigInteger啥的以便兼容

**Comment by XMZO** [comment]
自己加了自动转换，已成功修复

**Comment by XMZO** [comment]
byd核电工艺还用int

**Comment by XMZO** [comment]
> byd核电工艺还用int

也是修了

**Comment by XMZO** [comment]
仍然发现了其他的许多问题...不管了已放弃
